// This file was generated based on 'C:\ProgramData\Uno\Packages\UnoCore\0.13.2\Targets\CPlusPlus\Android\Source\Base\$.uno'.
// WARNING: Changes might be lost if you edit this file directly.

#ifndef __APP_ANDROID_BASE_J_N_I_H__
#define __APP_ANDROID_BASE_J_N_I_H__

#include <android/log.h>
#include <app/Uno.Exception.h>
#include <jni.h>
#include <JNIHelper.h>
#include <Uno.h>
#include <Xli.h>
#include <XliPlatform/PlatformSpecific/Android.h>
namespace app { namespace Android { namespace Base { namespace Wrappers { struct JWrapper; } } } }
namespace app { namespace Uno { struct Exception; } }

namespace app {
namespace Android {
namespace Base {

extern jmethodID JNI___getUnoRefMid;
extern jclass JNI___helperCls;
extern bool JNI___inited;
extern ::uStaticStrong< ::app::Android::Base::Wrappers::JWrapper*> JNI___rootActivityWrapped;
extern jmethodID JNI__Activity_getClassLoader;
extern jmethodID JNI__ClassLoader_loadClass;
extern jclass JNI__exceptionClass;

struct JNI__uType : ::uClassType
{
};

JNI__uType* JNI__typeof();

jboolean JNI__CallBooleanMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jboolean JNI__CallBooleanMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jboolean JNI__CallBooleanMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jboolean JNI__CallBooleanMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jboolean JNI__CallBooleanMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jboolean JNI__CallBooleanMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jboolean JNI__CallBooleanMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jboolean JNI__CallBooleanMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jboolean JNI__CallBooleanMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jboolean JNI__CallBooleanMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jboolean JNI__CallBooleanMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jboolean JNI__CallBooleanMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jbyte JNI__CallByteMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jbyte JNI__CallByteMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jbyte JNI__CallByteMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jbyte JNI__CallByteMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jbyte JNI__CallByteMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jbyte JNI__CallByteMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jbyte JNI__CallByteMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jbyte JNI__CallByteMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jbyte JNI__CallByteMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jbyte JNI__CallByteMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jbyte JNI__CallByteMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jbyte JNI__CallByteMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jchar JNI__CallCharMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jchar JNI__CallCharMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jchar JNI__CallCharMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jchar JNI__CallCharMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jchar JNI__CallCharMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jchar JNI__CallCharMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jchar JNI__CallCharMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jchar JNI__CallCharMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jchar JNI__CallCharMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jchar JNI__CallCharMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jchar JNI__CallCharMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jchar JNI__CallCharMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jdouble JNI__CallDoubleMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jdouble JNI__CallDoubleMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jdouble JNI__CallDoubleMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jdouble JNI__CallDoubleMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jdouble JNI__CallDoubleMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jdouble JNI__CallDoubleMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jdouble JNI__CallDoubleMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jdouble JNI__CallDoubleMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jdouble JNI__CallDoubleMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jdouble JNI__CallDoubleMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jdouble JNI__CallDoubleMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jdouble JNI__CallDoubleMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jfloat JNI__CallFloatMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jfloat JNI__CallFloatMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jfloat JNI__CallFloatMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jfloat JNI__CallFloatMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jfloat JNI__CallFloatMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jfloat JNI__CallFloatMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jfloat JNI__CallFloatMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jfloat JNI__CallFloatMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jfloat JNI__CallFloatMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jfloat JNI__CallFloatMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jfloat JNI__CallFloatMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jfloat JNI__CallFloatMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jint JNI__CallIntMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jint JNI__CallIntMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jint JNI__CallIntMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jint JNI__CallIntMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jint JNI__CallIntMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jint JNI__CallIntMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jint JNI__CallIntMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jint JNI__CallIntMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jint JNI__CallIntMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jint JNI__CallIntMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jint JNI__CallIntMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jint JNI__CallIntMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jlong JNI__CallLongMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jlong JNI__CallLongMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jlong JNI__CallLongMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jlong JNI__CallLongMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jlong JNI__CallLongMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jlong JNI__CallLongMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jlong JNI__CallLongMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jlong JNI__CallLongMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jlong JNI__CallLongMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jlong JNI__CallLongMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jlong JNI__CallLongMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jlong JNI__CallLongMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jboolean JNI__CallNonvirtualBooleanMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jboolean JNI__CallNonvirtualBooleanMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jboolean JNI__CallNonvirtualBooleanMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jboolean JNI__CallNonvirtualBooleanMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jboolean JNI__CallNonvirtualBooleanMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jboolean JNI__CallNonvirtualBooleanMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jboolean JNI__CallNonvirtualBooleanMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jboolean JNI__CallNonvirtualBooleanMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jboolean JNI__CallNonvirtualBooleanMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jboolean JNI__CallNonvirtualBooleanMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jboolean JNI__CallNonvirtualBooleanMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jboolean JNI__CallNonvirtualBooleanMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jbyte JNI__CallNonvirtualByteMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jbyte JNI__CallNonvirtualByteMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jbyte JNI__CallNonvirtualByteMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jbyte JNI__CallNonvirtualByteMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jbyte JNI__CallNonvirtualByteMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jbyte JNI__CallNonvirtualByteMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jbyte JNI__CallNonvirtualByteMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jbyte JNI__CallNonvirtualByteMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jbyte JNI__CallNonvirtualByteMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jbyte JNI__CallNonvirtualByteMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jbyte JNI__CallNonvirtualByteMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jbyte JNI__CallNonvirtualByteMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jchar JNI__CallNonvirtualCharMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jchar JNI__CallNonvirtualCharMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jchar JNI__CallNonvirtualCharMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jchar JNI__CallNonvirtualCharMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jchar JNI__CallNonvirtualCharMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jchar JNI__CallNonvirtualCharMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jchar JNI__CallNonvirtualCharMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jchar JNI__CallNonvirtualCharMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jchar JNI__CallNonvirtualCharMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jchar JNI__CallNonvirtualCharMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jchar JNI__CallNonvirtualCharMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jchar JNI__CallNonvirtualCharMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jdouble JNI__CallNonvirtualDoubleMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jdouble JNI__CallNonvirtualDoubleMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jdouble JNI__CallNonvirtualDoubleMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jdouble JNI__CallNonvirtualDoubleMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jdouble JNI__CallNonvirtualDoubleMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jdouble JNI__CallNonvirtualDoubleMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jdouble JNI__CallNonvirtualDoubleMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jdouble JNI__CallNonvirtualDoubleMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jdouble JNI__CallNonvirtualDoubleMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jdouble JNI__CallNonvirtualDoubleMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jdouble JNI__CallNonvirtualDoubleMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jdouble JNI__CallNonvirtualDoubleMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jfloat JNI__CallNonvirtualFloatMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jfloat JNI__CallNonvirtualFloatMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jfloat JNI__CallNonvirtualFloatMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jfloat JNI__CallNonvirtualFloatMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jfloat JNI__CallNonvirtualFloatMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jfloat JNI__CallNonvirtualFloatMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jfloat JNI__CallNonvirtualFloatMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jfloat JNI__CallNonvirtualFloatMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jfloat JNI__CallNonvirtualFloatMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jfloat JNI__CallNonvirtualFloatMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jfloat JNI__CallNonvirtualFloatMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jfloat JNI__CallNonvirtualFloatMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jint JNI__CallNonvirtualIntMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jint JNI__CallNonvirtualIntMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jint JNI__CallNonvirtualIntMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jint JNI__CallNonvirtualIntMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jint JNI__CallNonvirtualIntMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jint JNI__CallNonvirtualIntMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jint JNI__CallNonvirtualIntMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jint JNI__CallNonvirtualIntMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jint JNI__CallNonvirtualIntMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jint JNI__CallNonvirtualIntMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jint JNI__CallNonvirtualIntMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jint JNI__CallNonvirtualIntMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jlong JNI__CallNonvirtualLongMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jlong JNI__CallNonvirtualLongMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jlong JNI__CallNonvirtualLongMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jlong JNI__CallNonvirtualLongMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jlong JNI__CallNonvirtualLongMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jlong JNI__CallNonvirtualLongMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jlong JNI__CallNonvirtualLongMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jlong JNI__CallNonvirtualLongMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jlong JNI__CallNonvirtualLongMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jlong JNI__CallNonvirtualLongMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jlong JNI__CallNonvirtualLongMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jlong JNI__CallNonvirtualLongMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jobject JNI__CallNonvirtualObjectMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jobject JNI__CallNonvirtualObjectMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jobject JNI__CallNonvirtualObjectMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jobject JNI__CallNonvirtualObjectMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jobject JNI__CallNonvirtualObjectMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jobject JNI__CallNonvirtualObjectMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jobject JNI__CallNonvirtualObjectMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jobject JNI__CallNonvirtualObjectMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jobject JNI__CallNonvirtualObjectMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jobject JNI__CallNonvirtualObjectMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jobject JNI__CallNonvirtualObjectMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jobject JNI__CallNonvirtualObjectMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jshort JNI__CallNonvirtualShortMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
jshort JNI__CallNonvirtualShortMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
jshort JNI__CallNonvirtualShortMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jshort JNI__CallNonvirtualShortMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jshort JNI__CallNonvirtualShortMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jshort JNI__CallNonvirtualShortMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jshort JNI__CallNonvirtualShortMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jshort JNI__CallNonvirtualShortMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jshort JNI__CallNonvirtualShortMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jshort JNI__CallNonvirtualShortMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jshort JNI__CallNonvirtualShortMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jshort JNI__CallNonvirtualShortMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
void JNI__CallNonvirtualVoidMethod(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd);
void JNI__CallNonvirtualVoidMethod_1(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0);
void JNI__CallNonvirtualVoidMethod_10(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
void JNI__CallNonvirtualVoidMethod_11(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
void JNI__CallNonvirtualVoidMethod_2(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
void JNI__CallNonvirtualVoidMethod_3(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
void JNI__CallNonvirtualVoidMethod_4(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
void JNI__CallNonvirtualVoidMethod_5(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
void JNI__CallNonvirtualVoidMethod_6(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
void JNI__CallNonvirtualVoidMethod_7(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
void JNI__CallNonvirtualVoidMethod_8(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
void JNI__CallNonvirtualVoidMethod_9(::uStatic* __this, jobject obj, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jobject JNI__CallObjectMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jobject JNI__CallObjectMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jobject JNI__CallObjectMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jobject JNI__CallObjectMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jobject JNI__CallObjectMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jobject JNI__CallObjectMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jobject JNI__CallObjectMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jobject JNI__CallObjectMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jobject JNI__CallObjectMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jobject JNI__CallObjectMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jobject JNI__CallObjectMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jobject JNI__CallObjectMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jshort JNI__CallShortMethod(::uStatic* __this, jobject obj, jmethodID mtd);
jshort JNI__CallShortMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
jshort JNI__CallShortMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jshort JNI__CallShortMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jshort JNI__CallShortMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
jshort JNI__CallShortMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jshort JNI__CallShortMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jshort JNI__CallShortMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jshort JNI__CallShortMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jshort JNI__CallShortMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jshort JNI__CallShortMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jshort JNI__CallShortMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jboolean JNI__CallStaticBooleanMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jboolean JNI__CallStaticBooleanMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jboolean JNI__CallStaticBooleanMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jboolean JNI__CallStaticBooleanMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jboolean JNI__CallStaticBooleanMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jboolean JNI__CallStaticBooleanMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jboolean JNI__CallStaticBooleanMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jboolean JNI__CallStaticBooleanMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jboolean JNI__CallStaticBooleanMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jboolean JNI__CallStaticBooleanMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jboolean JNI__CallStaticBooleanMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jboolean JNI__CallStaticBooleanMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jbyte JNI__CallStaticByteMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jbyte JNI__CallStaticByteMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jbyte JNI__CallStaticByteMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jbyte JNI__CallStaticByteMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jbyte JNI__CallStaticByteMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jbyte JNI__CallStaticByteMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jbyte JNI__CallStaticByteMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jbyte JNI__CallStaticByteMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jbyte JNI__CallStaticByteMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jbyte JNI__CallStaticByteMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jbyte JNI__CallStaticByteMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jbyte JNI__CallStaticByteMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jchar JNI__CallStaticCharMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jchar JNI__CallStaticCharMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jchar JNI__CallStaticCharMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jchar JNI__CallStaticCharMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jchar JNI__CallStaticCharMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jchar JNI__CallStaticCharMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jchar JNI__CallStaticCharMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jchar JNI__CallStaticCharMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jchar JNI__CallStaticCharMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jchar JNI__CallStaticCharMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jchar JNI__CallStaticCharMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jchar JNI__CallStaticCharMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jdouble JNI__CallStaticDoubleMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jdouble JNI__CallStaticDoubleMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jdouble JNI__CallStaticDoubleMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jdouble JNI__CallStaticDoubleMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jdouble JNI__CallStaticDoubleMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jdouble JNI__CallStaticDoubleMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jdouble JNI__CallStaticDoubleMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jdouble JNI__CallStaticDoubleMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jdouble JNI__CallStaticDoubleMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jdouble JNI__CallStaticDoubleMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jdouble JNI__CallStaticDoubleMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jdouble JNI__CallStaticDoubleMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jfloat JNI__CallStaticFloatMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jfloat JNI__CallStaticFloatMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jfloat JNI__CallStaticFloatMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jfloat JNI__CallStaticFloatMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jfloat JNI__CallStaticFloatMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jfloat JNI__CallStaticFloatMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jfloat JNI__CallStaticFloatMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jfloat JNI__CallStaticFloatMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jfloat JNI__CallStaticFloatMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jfloat JNI__CallStaticFloatMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jfloat JNI__CallStaticFloatMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jfloat JNI__CallStaticFloatMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jint JNI__CallStaticIntMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jint JNI__CallStaticIntMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jint JNI__CallStaticIntMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jint JNI__CallStaticIntMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jint JNI__CallStaticIntMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jint JNI__CallStaticIntMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jint JNI__CallStaticIntMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jint JNI__CallStaticIntMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jint JNI__CallStaticIntMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jint JNI__CallStaticIntMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jint JNI__CallStaticIntMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jint JNI__CallStaticIntMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jlong JNI__CallStaticLongMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jlong JNI__CallStaticLongMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jlong JNI__CallStaticLongMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jlong JNI__CallStaticLongMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jlong JNI__CallStaticLongMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jlong JNI__CallStaticLongMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jlong JNI__CallStaticLongMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jlong JNI__CallStaticLongMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jlong JNI__CallStaticLongMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jlong JNI__CallStaticLongMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jlong JNI__CallStaticLongMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jlong JNI__CallStaticLongMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jobject JNI__CallStaticObjectMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jobject JNI__CallStaticObjectMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jobject JNI__CallStaticObjectMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jobject JNI__CallStaticObjectMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jobject JNI__CallStaticObjectMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jobject JNI__CallStaticObjectMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jobject JNI__CallStaticObjectMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jobject JNI__CallStaticObjectMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jobject JNI__CallStaticObjectMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jobject JNI__CallStaticObjectMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jobject JNI__CallStaticObjectMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jobject JNI__CallStaticObjectMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jshort JNI__CallStaticShortMethod(::uStatic* __this, jclass cls, jmethodID mtd);
jshort JNI__CallStaticShortMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jshort JNI__CallStaticShortMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jshort JNI__CallStaticShortMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jshort JNI__CallStaticShortMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jshort JNI__CallStaticShortMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jshort JNI__CallStaticShortMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jshort JNI__CallStaticShortMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jshort JNI__CallStaticShortMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jshort JNI__CallStaticShortMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jshort JNI__CallStaticShortMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jshort JNI__CallStaticShortMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
void JNI__CallStaticVoidMethod(::uStatic* __this, jclass cls, jmethodID mtd);
void JNI__CallStaticVoidMethod_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
void JNI__CallStaticVoidMethod_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
void JNI__CallStaticVoidMethod_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
void JNI__CallStaticVoidMethod_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
void JNI__CallStaticVoidMethod_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
void JNI__CallStaticVoidMethod_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
void JNI__CallStaticVoidMethod_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
void JNI__CallStaticVoidMethod_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
void JNI__CallStaticVoidMethod_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
void JNI__CallStaticVoidMethod_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
void JNI__CallStaticVoidMethod_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
void JNI__CallVoidMethod(::uStatic* __this, jobject obj, jmethodID mtd);
void JNI__CallVoidMethod_1(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0);
void JNI__CallVoidMethod_10(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
void JNI__CallVoidMethod_11(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
void JNI__CallVoidMethod_2(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1);
void JNI__CallVoidMethod_3(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
void JNI__CallVoidMethod_4(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
void JNI__CallVoidMethod_5(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
void JNI__CallVoidMethod_6(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
void JNI__CallVoidMethod_7(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
void JNI__CallVoidMethod_8(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
void JNI__CallVoidMethod_9(::uStatic* __this, jobject obj, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
void JNI__CheckException(::uStatic* __this);
void JNI__CheckException_1(::uStatic* __this, JNIEnv* jni);
void JNI__CheckException_2(::uStatic* __this, JNIEnv* jni, ::uString* appendMessage);
void JNI__DeleteGlobalRef(::uStatic* __this, jobject obj_);
void JNI__DeleteLocalRef(::uStatic* __this, jclass obj);
void JNI__DeleteLocalRef_1(::uStatic* __this, jobject obj);
void JNI__DeleteLocalRef_2(::uStatic* __this, jstring obj);
void JNI__DeleteWeakGlobalRef(::uStatic* __this, jobject obj_);
jclass JNI__GetActivityClass(::uStatic* __this);
jobject JNI__GetActivityObject(::uStatic* __this);
int JNI__GetArrayLength(::uStatic* __this, jobject array_);
bool JNI__GetBooleanArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
bool JNI__GetBooleanField(::uStatic* __this, jobject obj, jfieldID fld);
::uSByte JNI__GetByteArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
::uSByte JNI__GetByteField(::uStatic* __this, jobject obj, jfieldID fld);
::uChar JNI__GetCharArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
::uChar JNI__GetCharField(::uStatic* __this, jobject obj, jfieldID fld);
jobject JNI__GetDefaultObject(::uStatic* __this);
::uType* JNI__GetDefaultType(::uStatic* __this);
double JNI__GetDoubleArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
double JNI__GetDoubleField(::uStatic* __this, jobject obj, jfieldID fld);
JNIEnv* JNI__GetEnvPtr(::uStatic* __this);
jfieldID JNI__GetFieldID(::uStatic* __this, jclass cls, ::uString* fieldName, ::uString* fieldSig);
float JNI__GetFloatArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
float JNI__GetFloatField(::uStatic* __this, jobject obj, jfieldID fld);
int JNI__GetIntArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
int JNI__GetIntField(::uStatic* __this, jobject obj, jfieldID fld);
::uLong JNI__GetLongArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
::uLong JNI__GetLongField(::uStatic* __this, jobject obj, jfieldID fld);
jmethodID JNI__GetMethodID(::uStatic* __this, jclass cls, ::uString* methodName, ::uString* methodSig);
jobject JNI__GetObjectArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
jobject JNI__GetObjectField(::uStatic* __this, jobject obj, jfieldID fld);
::app::Android::Base::Wrappers::JWrapper* JNI__GetObjectFieldWrapped(::uStatic* __this, jobject obj, jfieldID fld);
int JNI__GetRefType(::uStatic* __this, JNIEnv* jni, jobject obj);
int JNI__GetRefType_1(::uStatic* __this, jobject obj);
::uShort JNI__GetShortArrayElement(::uStatic* __this, ::uObject* obj_, int i_);
::uShort JNI__GetShortField(::uStatic* __this, jobject obj, jfieldID fld);
bool JNI__GetStaticBooleanField(::uStatic* __this, jclass obj, jfieldID fld);
::uSByte JNI__GetStaticByteField(::uStatic* __this, jclass obj, jfieldID fld);
::uChar JNI__GetStaticCharField(::uStatic* __this, jclass obj, jfieldID fld);
double JNI__GetStaticDoubleField(::uStatic* __this, jclass obj, jfieldID fld);
jfieldID JNI__GetStaticFieldID(::uStatic* __this, jclass cls, ::uString* fieldName, ::uString* fieldSig);
float JNI__GetStaticFloatField(::uStatic* __this, jclass obj, jfieldID fld);
int JNI__GetStaticIntField(::uStatic* __this, jclass obj, jfieldID fld);
::uLong JNI__GetStaticLongField(::uStatic* __this, jclass obj, jfieldID fld);
jmethodID JNI__GetStaticMethodID(::uStatic* __this, jclass cls, ::uString* methodName, ::uString* methodSig);
jobject JNI__GetStaticObjectField(::uStatic* __this, jclass obj, jfieldID fld);
::app::Android::Base::Wrappers::JWrapper* JNI__GetStaticObjectFieldWrapped(::uStatic* __this, jclass obj, jfieldID fld);
::uShort JNI__GetStaticShortField(::uStatic* __this, jclass obj, jfieldID fld);
::uLong JNI__GetUnoRef(::uStatic* __this, jobject obj_);
JavaVM* JNI__GetVM(::uStatic* __this);
::app::Android::Base::Wrappers::JWrapper* JNI__GetWrappedActivityObject(::uStatic* __this);
void JNI__Init(::uStatic* __this);
bool JNI__IsSameObject(::uStatic* __this, jobject objA_, jobject objB_);
jclass JNI__LoadClass(::uStatic* __this, JNIEnv* jni, const char* name);
jclass JNI__LoadClass_1(::uStatic* __this, JNIEnv* jni, const char* name, bool systemClass);
jclass JNI__LoadClass_2(::uStatic* __this, JNIEnv* jni, ::uString* name, bool systemClass);
jclass JNI__LoadClass_3(::uStatic* __this, ::uString* name, bool systemClass);
jclass JNI__LocalToGlobalRef(::uStatic* __this, jclass obj);
jobject JNI__LocalToGlobalRef_1(::uStatic* __this, jobject obj);
jstring JNI__LocalToGlobalRef_2(::uStatic* __this, jstring obj);
jobject JNI__NewBooleanArray(::uStatic* __this, int len_);
jobject JNI__NewByteArray(::uStatic* __this, int len_);
jobject JNI__NewCharArray(::uStatic* __this, int len_);
jobject JNI__NewDoubleArray(::uStatic* __this, int len_);
jobject JNI__NewFloatArray(::uStatic* __this, int len_);
jclass JNI__NewGlobalRef(::uStatic* __this, jclass obj);
jobject JNI__NewGlobalRef_1(::uStatic* __this, jobject obj_);
jstring JNI__NewGlobalRef_2(::uStatic* __this, jstring obj);
jobject JNI__NewIntArray(::uStatic* __this, int len_);
jobject JNI__NewLongArray(::uStatic* __this, int len_);
jobject JNI__NewObject(::uStatic* __this, jclass cls, jmethodID mtd);
jobject JNI__NewObject_1(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0);
jobject JNI__NewObject_10(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9);
jobject JNI__NewObject_11(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8, jvalue arg9, jvalue arg10);
jobject JNI__NewObject_2(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1);
jobject JNI__NewObject_3(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2);
jobject JNI__NewObject_4(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3);
jobject JNI__NewObject_5(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4);
jobject JNI__NewObject_6(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5);
jobject JNI__NewObject_7(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6);
jobject JNI__NewObject_8(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7);
jobject JNI__NewObject_9(::uStatic* __this, jclass cls, jmethodID mtd, jvalue arg0, jvalue arg1, jvalue arg2, jvalue arg3, jvalue arg4, jvalue arg5, jvalue arg6, jvalue arg7, jvalue arg8);
jobject JNI__NewObjectArray(::uStatic* __this, jclass cls_, int len_);
jobject JNI__NewShortArray(::uStatic* __this, int len_);
jobject JNI__NewWeakGlobalRef(::uStatic* __this, jobject obj_);
void JNI__SetBooleanArrayElement(::uStatic* __this, ::uObject* obj_, int i_, bool val_);
void JNI__SetByteArrayElement(::uStatic* __this, ::uObject* obj_, int i_, ::uSByte val_);
void JNI__SetCharArrayElement(::uStatic* __this, ::uObject* obj_, int i_, ::uChar val_);
void JNI__SetDoubleArrayElement(::uStatic* __this, ::uObject* obj_, int i_, double val_);
void JNI__SetFloatArrayElement(::uStatic* __this, ::uObject* obj_, int i_, float val_);
void JNI__SetIntArrayElement(::uStatic* __this, ::uObject* obj_, int i_, int val_);
void JNI__SetLongArrayElement(::uStatic* __this, ::uObject* obj_, int i_, ::uLong val_);
void JNI__SetObjectArrayElement(::uStatic* __this, ::uObject* obj_, int i_, jobject val_);
void JNI__SetShortArrayElement(::uStatic* __this, ::uObject* obj_, int i_, ::uShort val_);
void JNI__ThrowNewException(::uStatic* __this, ::uString* message_);
::app::Uno::Exception* JNI__TryGetException(::uStatic* __this, JNIEnv* jni, ::uString* appendMessage);

}}}


#endif
